version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-compose/pgsql:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    env_file: .env
    ports:
      - "6001:6379"
    volumes:
      - ./docker-compose/redis:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    env_file: .env
    environment:
    - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads/images:/usr/src/app/uploads/images #supaya aplikasi NestJS bisa menyimpan atau membaca file upload di folder tersebut, dan data file tetap tersimpan di host (bukan di dalam container).
    command: npm run start:dev
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker-compose/nginx/logs:/var/log/nginx
      - ./uploads/images:/usr/src/app/uploads/images #supaya Nginx bisa serve file statis (gambar upload) langsung dari host dengan akses cepat tanpa lewat aplikasi backend.
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge