# Use version 3.8 of the Docker Compose file format
version: '3.8'

services:
  api:
    container_name: nestjs-boilerplate
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3000
      - DATABASE_URL=postgresql://edwinhendrian:@localhost:5432/random_db
      - JWT_SECRET='rahasia'
volumes:
  uploads_data: